modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
issueTrackerURL="https://github.com/dhyces/prize-machines/issues" #optional
[[mods]] #mandatory
modId="prizemachines" #mandatory
version="1.1.0" #mandatory
displayName="Prize Machines Mod" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="icon.png"
authors="Dhyces, Kawa DW, PROhitman" #optional
description='''Adds prize machines.'''

[[mixins]]
config="prizemachines.mixins.json"

[[dependencies.neoforge]] #optional
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.minecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"